export const REQUEST = {
  ALL_TAG: '/api/work/tag/all',
  WORK_TAG: '/api/work/tag',
  BEST_TODAY: '/api/work/best/today',
  MONTHLY_POPULAR_WORK: '/api/work/popular/monthly',
  MONTHLY_BEST_AUTHOR: '/api/work/author/best/monthly',
  RECOMMEND_WEBTOON: '/api/work/recommend/webtoon',
  RECOMMEND_POEM: '/api/work/recommend/poem',
  RECOMMEND_NOVEL: '/api/work/recommend/novel',
  NEW_WORK: '/api/work/new',
  NEW_AUTHOR: '/api/authors/new/author',
  KEYWORDS: '/api/work/search/popular',
  SEARCH: '/api/work/search',
  LOGIN: '/api/member/signin',
};
